#!/usr/bin/env bash
# Regenerate specs/ROADMAP.md from the spec kit artefacts on disk.
#
# The roadmap is DERIVED, never hand-edited: the stage of a feature is whatever its
# directory proves (spec.md → plan.md → tasks.md → all tasks checked), and the
# priority/summary come from the `**Priority**:` / `**Summary**:` header lines of
# its spec.md. Edit the spec, not the roadmap.
#
# Usage: roadmap.sh [--check] [--stdout]
#   --check   exit 1 if specs/ROADMAP.md is stale (does not write)
#   --stdout  print the roadmap instead of writing it

set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
out="$root/specs/ROADMAP.md"
mode=write
for arg in "$@"; do
    case "$arg" in
        --check) mode=check ;;
        --stdout) mode=stdout ;;
        *) echo "roadmap.sh: unknown option $arg" >&2; exit 2 ;;
    esac
done

# Value of a `**Key**: value` header line (first match, first 40 lines of the spec).
header() {
    sed -n '1,40p' "$1" | sed -n "s/^\*\*$2\*\*:[[:space:]]*//p" | head -n1
}

active=""
if [[ -f "$root/.specify/feature.json" ]]; then
    active="$(sed -n 's/.*"feature_directory"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' \
        "$root/.specify/feature.json" | head -n1)"
fi

render() {
    cat <<'EOF'
# Roadmap

<!-- GENERATED by .specify/scripts/xxh/roadmap.sh — do not edit by hand.
     Stage is derived from the artefacts in each feature directory; priority and
     summary come from the `**Priority**` / `**Summary**` lines of its spec.md. -->

Все фичи проекта ведутся через spec kit: одна фича — один каталог `specs/NNN-имя/`.
Стадия: `spec` → `plan` → `tasks` → `implement N/M` → `done`.

| № | Фича | Приоритет | Стадия | Вопросы | Суть |
|---|------|-----------|--------|---------|------|
EOF
    local dir name num title prio summary stage total done_n open mark
    for dir in "$root"/specs/[0-9][0-9][0-9]-*/; do
        [[ -f "$dir/spec.md" ]] || continue
        name="$(basename "$dir")"
        num="${name%%-*}"
        title="$(sed -n '1s/^# Feature Specification:[[:space:]]*//p' "$dir/spec.md")"
        [[ -n "$title" ]] || title="${name#*-}"
        prio="$(header "$dir/spec.md" Priority)"
        summary="$(header "$dir/spec.md" Summary)"
        open="$(grep -c 'NEEDS CLARIFICATION' "$dir/spec.md" || true)"

        if [[ -f "$dir/tasks.md" ]]; then
            total="$(grep -cE '^- \[[ xX]\] T[0-9]+' "$dir/tasks.md" || true)"
            done_n="$(grep -cE '^- \[[xX]\] T[0-9]+' "$dir/tasks.md" || true)"
            if [[ "$total" -gt 0 && "$done_n" -eq "$total" ]]; then
                stage="done"
            elif [[ "$done_n" -eq 0 ]]; then
                stage="tasks 0/$total"
            else
                stage="implement $done_n/$total"
            fi
        elif [[ -f "$dir/plan.md" ]]; then
            stage="plan"
        else
            stage="spec"
        fi

        # A literal `|` would split the table cell.
        title="${title//|/\\|}"
        summary="${summary//|/\\|}"

        mark=""
        [[ "specs/$name" == "$active" ]] && mark=" ◀"
        printf '| %s | [%s](%s/spec.md)%s | %s | %s | %s | %s |\n' \
            "$num" "$title" "$name" "$mark" "${prio:-—}" "$stage" \
            "$([[ "$open" -gt 0 ]] && echo "$open" || echo "—")" "${summary:-—}"
    done
    printf '\n`◀` — активная фича (`.specify/feature.json`).\n'
}

case "$mode" in
    stdout) render ;;
    check)
        if [[ -f "$out" ]] && diff -q <(render) "$out" >/dev/null; then
            exit 0
        fi
        echo "specs/ROADMAP.md is stale — run .specify/scripts/xxh/roadmap.sh" >&2
        exit 1
        ;;
    write)
        tmp="$(mktemp "$out.XXXXXX")"
        render >"$tmp"
        mv "$tmp" "$out"
        ;;
esac
