//! The lock file: what exactly a declared plugin or shell was installed from
//! (013 C-L2..C-L3).
//!
//! `xxh.lock` sits next to the config. Each entry records the source string as
//! declared, the git revision when the source is git, and the content hash.
//! Entries are kept in name order and written atomically, so an unchanged lock
//! is byte-for-byte the same — fit for version control (§FR-008). It holds
//! versions, never settings (§FR-011).

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};
use xxh_plugin_api::PluginError;

/// One locked plugin or shell.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct LockEntry {
    /// The source exactly as declared in the config.
    pub source: String,
    /// The git commit it was installed from, for git sources.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub revision: Option<String>,
    /// Content hash of what was installed.
    pub hash: String,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct Lock {
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub plugins: BTreeMap<String, LockEntry>,
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub shells: BTreeMap<String, LockEntry>,
}

const HEADER: &str = "# Generated by `xxh sync` / `xxh plugin update`: the exact versions of the\n\
# plugins and shells declared in config.toml. Commit it with the config.\n";

/// `$XXH_LOCK_FILE`, else `xxh.lock` next to the config file.
pub fn default_path(config_path: &Path) -> PathBuf {
    match std::env::var_os("XXH_LOCK_FILE") {
        Some(p) => PathBuf::from(p),
        None => config_path
            .parent()
            .map_or_else(|| PathBuf::from("xxh.lock"), |d| d.join("xxh.lock")),
    }
}

impl Lock {
    /// Read a lock file; a missing one is empty.
    pub fn load(path: &Path) -> Result<Self, PluginError> {
        match std::fs::read_to_string(path) {
            Ok(text) => toml::from_str(&text).map_err(|e| {
                PluginError::Other(format!("invalid lock file {}: {e}", path.display()))
            }),
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(Self::default()),
            Err(e) => Err(PluginError::Other(format!(
                "reading lock file {}: {e}",
                path.display()
            ))),
        }
    }

    /// The deterministic text of the lock (C-L3).
    pub fn render(&self) -> String {
        format!(
            "{HEADER}\n{}",
            toml::to_string_pretty(self).expect("a lock always serializes")
        )
    }

    /// Write atomically (temp file + rename).
    pub fn save(&self, path: &Path) -> std::io::Result<()> {
        if let Some(dir) = path.parent() {
            std::fs::create_dir_all(dir)?;
        }
        let tmp = path.with_extension(format!("lock.tmp-{}", std::process::id()));
        std::fs::write(&tmp, self.render())?;
        std::fs::rename(&tmp, path)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn entry(source: &str, rev: Option<&str>, hash: &str) -> LockEntry {
        LockEntry {
            source: source.into(),
            revision: rev.map(str::to_string),
            hash: hash.into(),
        }
    }

    #[test]
    fn lock_round_trips_and_writes_identical_bytes() {
        let dir = std::env::temp_dir().join(format!("xxh-lock-{}", std::process::id()));
        let path = dir.join("xxh.lock");
        assert_eq!(
            Lock::load(&path).unwrap(),
            Lock::default(),
            "missing = empty"
        );

        let mut lock = Lock::default();
        lock.plugins
            .insert("zeta".into(), entry("nixpkgs:htop", None, "aa"));
        lock.plugins
            .insert("alpha".into(), entry("git@h:me/p.git", Some("0123"), "bb"));
        lock.shells
            .insert("zsh".into(), entry("/src/zsh", None, "cc"));
        lock.save(&path).unwrap();
        let first = std::fs::read(&path).unwrap();
        assert_eq!(Lock::load(&path).unwrap(), lock);
        lock.save(&path).unwrap();
        assert_eq!(std::fs::read(&path).unwrap(), first, "byte-for-byte stable");

        let text = String::from_utf8(first).unwrap();
        assert!(text.starts_with("# Generated by"), "{text}");
        assert!(
            text.find("[plugins.alpha]").unwrap() < text.find("[plugins.zeta]").unwrap(),
            "name order"
        );
        assert!(
            !text.contains("revision = \"\""),
            "no empty revision for nixpkgs"
        );
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn lock_path_sits_next_to_the_config() {
        // Without the override (tests never set it).
        if std::env::var_os("XXH_LOCK_FILE").is_none() {
            assert_eq!(
                default_path(Path::new("/home/u/.config/xxh/config.toml")),
                PathBuf::from("/home/u/.config/xxh/xxh.lock")
            );
        }
    }
}
